CREATE TABLE IF NO EXISTS accom.bookings(
    id BIGINT PRIMARY NOT NULL GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT NOT NULL,
    "provider" VARCHAR(100) NOT NULL,
    "hash" VARCHAR(64) NOT NULL,
    "reference" UUID NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)